// <auto-generated />
using System;
using LuckyLottery.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LuckyLottery.Migrations
{
    [DbContext(typeof(LotteryDbContext))]
    partial class LotteryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LuckyLottery.Models.EuroMillionenAtDraw", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DrawDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("N1")
                        .HasColumnType("int");

                    b.Property<int>("N2")
                        .HasColumnType("int");

                    b.Property<int>("N3")
                        .HasColumnType("int");

                    b.Property<int>("N4")
                        .HasColumnType("int");

                    b.Property<int>("N5")
                        .HasColumnType("int");

                    b.Property<int>("Star1")
                        .HasColumnType("int");

                    b.Property<int>("Star2")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("EuroMillionenAtDraws");
                });

            modelBuilder.Entity("LuckyLottery.Models.EuroMillionenAtPlayedCombination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatePlayed")
                        .HasColumnType("datetime2");

                    b.Property<int>("Matches")
                        .HasColumnType("int");

                    b.Property<int>("N1")
                        .HasColumnType("int");

                    b.Property<int>("N2")
                        .HasColumnType("int");

                    b.Property<int>("N3")
                        .HasColumnType("int");

                    b.Property<int>("N4")
                        .HasColumnType("int");

                    b.Property<int>("N5")
                        .HasColumnType("int");

                    b.Property<int>("Star1")
                        .HasColumnType("int");

                    b.Property<int>("Star2")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("EuroMillionenAtPlayedCombinations");
                });

            modelBuilder.Entity("LuckyLottery.Models.LottoAtDraw", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DrawDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("N1")
                        .HasColumnType("int");

                    b.Property<int>("N2")
                        .HasColumnType("int");

                    b.Property<int>("N3")
                        .HasColumnType("int");

                    b.Property<int>("N4")
                        .HasColumnType("int");

                    b.Property<int>("N5")
                        .HasColumnType("int");

                    b.Property<int>("N6")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("LottoAtDraws");
                });

            modelBuilder.Entity("LuckyLottery.Models.LottoAtPlayedCombinations", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatePlayed")
                        .HasColumnType("datetime2");

                    b.Property<int>("Matches")
                        .HasColumnType("int");

                    b.Property<int>("N1")
                        .HasColumnType("int");

                    b.Property<int>("N2")
                        .HasColumnType("int");

                    b.Property<int>("N3")
                        .HasColumnType("int");

                    b.Property<int>("N4")
                        .HasColumnType("int");

                    b.Property<int>("N5")
                        .HasColumnType("int");

                    b.Property<int>("N6")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("LottoAtPlayedCombinations");
                });
#pragma warning restore 612, 618
        }
    }
}
